FROM golang:1.26 AS builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY pkg/ pkg/
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o onDefineDomain ./cmd/sidecar-hook/

FROM quay.io/kubevirt/sidecar-shim:v1.8.2
COPY --from=builder /workspace/onDefineDomain /usr/bin/onDefineDomain
ENTRYPOINT ["/sidecar-shim", "--version", "v1alpha2"]
